name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6.17
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies and Test
        run: yarn install
      - name: Build
        run: yarn run build
      - name: Lint
        run: yarn run lint
      - name: Test
        run: yarn run test
        env:
          PORT: 12000
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASSWORD: postgres
          PGPORT: 5432
          PGSSL: false

      - name: Version
        run: "scripts/run-in-packages.sh yarn version --no-git-tag-version --new-version 0.0.99"
      - name: Repush
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'githubactions'
          git commit -am "v0.0.99"
          git tag -a "v0.0.99" -m "v0.0.99"
          git branch -va
          git push
